import { colors } from '@/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, justifyContent: 'flex-start', backgroundColor: colors.background },
  page: { flex: 1, justifyContent: 'flex-start', paddingHorizontal: 20 },
  actions: { flexDirection: 'row', alignItems: 'stretch', gap: 10, marginBottom: 10 },
  addButton: {
    flex: 1, minWidth: 0,
    minHeight: 48, alignItems: 'center', justifyContent: 'center',
    paddingHorizontal: 16, paddingVertical: 12,
    borderRadius: 12, backgroundColor: colors.primary,
  },
  addButtonText: { color: colors.surface, fontSize: 15, fontWeight: '800' },
  filtersToggle: {
    width: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center',
    borderRadius: 12, borderWidth: 1, borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filtersToggleOpen: { backgroundColor: colors.softGreen, borderColor: colors.secondary },
  filterIcon: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center' },
  filterFunnel: {
    width: 20, height: 0, borderLeftWidth: 8, borderRightWidth: 8, borderTopWidth: 10,
    borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: colors.secondary,
  },
  filterStem: { width: 4, height: 7, backgroundColor: colors.secondary, borderBottomLeftRadius: 1, borderBottomRightRadius: 1 },
  filterBadge: {
    position: 'absolute', top: 2, right: 2, minWidth: 16, height: 16, borderRadius: 8,
    backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3,
  },
  filterBadgeText: { color: colors.surface, fontSize: 10, fontWeight: '800' },
  search: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 13,
    marginBottom: 10,
  },
  filters: { flexDirection: 'row', gap: 8, paddingBottom: 10 },
  priceTrigger: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  priceOptionSelected: { backgroundColor: colors.softGreen },
  mini: {
    flex: 1,
    height: 38,
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    fontSize: 13,
  },
  dropdownTrigger: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    minHeight: 44, paddingHorizontal: 12, borderRadius: 10,
    backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border,
    marginBottom: 10,
  },
  dropdownLabel: { fontSize: 13, color: colors.text, flexShrink: 1 },
  dropdown: {
    borderWidth: 1, borderColor: colors.border, borderRadius: 10,
    backgroundColor: colors.surface, marginBottom: 10, overflow: 'hidden',
  },
  options: { flexGrow: 0, maxHeight: 180 },
  option: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44, paddingHorizontal: 12 },
  checkbox: {
    width: 22, height: 22, borderRadius: 5, borderWidth: 1, borderColor: colors.border,
    alignItems: 'center', justifyContent: 'center',
  },
  checkboxSelected: { backgroundColor: colors.secondary, borderColor: colors.secondary },
  checkmark: { color: colors.surface, fontWeight: '800' },
  list: { justifyContent: 'flex-start', paddingBottom: 28 },
  empty: { paddingTop: 12, alignItems: 'flex-start' },
  emptyTitle: { fontSize: 20, fontWeight: '900', color: colors.text },
  emptyText: { fontSize: 14, color: colors.muted, marginTop: 8 },
});
