import { colors } from '@/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 17,
    marginBottom: 11,
    borderWidth: 1,
    borderColor: '#EEE6DE',
  },
  top: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  nameArea: { flex: 1, minWidth: 0 },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapsIcon: { backgroundColor: colors.softGreen },
  googleIcon: { backgroundColor: colors.softSand },
  mapsSymbol: { color: '#276559', fontSize: 28, fontWeight: '900' },
  googleSymbol: { color: '#4285F4', fontSize: 23, fontWeight: '900' },
  chevron: {
    width: 10,
    height: 10,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: colors.muted,
    transform: [{ rotate: '45deg' }],
  },
  chevronExpanded: { transform: [{ rotate: '225deg' }] },
  details: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#EEE6DE',
  },
  deleteButton: {
    alignSelf: 'flex-end',
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginTop: 8,
  },
  title: { fontSize: 19, fontWeight: '900', color: colors.text },
  metadata: {
    flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginTop: 8,
  },
  locality: { color: colors.muted, flexShrink: 1 },
  price: { color: colors.text, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  recommendedBy: { color: colors.muted, fontSize: 12, marginTop: 8 },
  delete: { color: colors.danger, fontSize: 12, fontWeight: '700' },
  tag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.softGreen,
    color: '#276559',
    fontWeight: '800',
    fontSize: 12,
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 12,
    overflow: 'hidden',
  },
  info: { marginBottom: 8 },
  infoLabel: {
    color: '#9A9088',
    fontWeight: '800',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoText: { color: '#49413B', marginTop: 2, lineHeight: 20 },
});
